### ISSUE TITLE
`?` causes infinite loop

### ISSUE THREAD

**Issue by spencerminer** [eigenhombre/l1#25]
```
> (quote can i have spaces?)

```
- [x] handle `atomsomething?`
- [x] also handle `$^[]{}&`
- [x] do something better than infinitely loop if another character fails to parse

**Comment by biiwide** [comment]
Several other characters also appear to trigger this behavior, including `$^[]{}&`.

**Comment by eigenhombre** [comment]
Fixed in `master` by actually wiring in lexing/parsing errors correctly.  Thanks for the bug reports, @spencerminer & @biiwide !
